# Site settings
# Notlarında Yer Alıyordu, Serbest Düşünce Akışı, Karanlık Sanatlara Karşı Savunma Dersi.
title: Tozbulut - Gezegendeki Olası Hayatlardan Birinin Bir Tarifnamesi

description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/skeletontest" # the subpath of your site, e.g. /blog
url: "http://tozbulut.github.io/" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

collections_dir: my_collections
paginate: 8
paginate_path: "/page/:num"
